from typing import TypedDict, List, Dict, Any, Optional, TYPE_CHECKING
from typing_extensions import Annotated
from langchain_core.messages import BaseMessage
import operator

if TYPE_CHECKING:
    from .graph import SynthesisResponse

class AgenticRunState(TypedDict):
    """
    Enhanced state schema for agentic QIA with built-in ReAct agent
    """
    # Original inputs
    prompt: str
    company_context: Optional[Dict[str, Any]]
    datapoint_definition: Optional[Dict[str, Any]]
    tool_registry: Optional[Dict[str, Any]]

    # Planning outputs (from triage)
    goal: str  # What information to find
    instructions: str  # How to find it (high-level plan)
    stopping_criteria: str  # When to stop searching
    obtainability: str  # low|medium|high difficulty assessment
    tools_budgeting: Dict[str, int]  # {max_queries, max_pages, max_seconds, max_evidence_tokens, max_ai_overviews}
    dp_contract: Optional[Dict[str, Any]]  # {dp_id: str}

    # Built-in ReAct agent state
    messages: Annotated[List[BaseMessage], operator.add]  # LangGraph message format
    _thread_id: Optional[str]  # Thread ID for budget tracking
    remaining_steps: Optional[int]  # For loop protection (used by create_react_agent)

    # Budget tracking
    loop_iteration: int
    budget_remaining: Dict[str, int]  # Real-time budget tracking
    usage: Dict[str, int]  # Current usage counters

    # Evidence (kept for backward compatibility with synthesis)
    tool_calls: Annotated[List[Dict[str, Any]], operator.add]  # Tool call history
    evidence_collected: Annotated[List[Dict[str, Any]], operator.add]  # Crawled pages
    candidates: Annotated[List[Dict[str, Any]], operator.add]  # SERP results
    discovered_urls: Annotated[List[str], operator.add]  # From discover_urls tool
    ai_overview_content: Annotated[List[Dict[str, Any]], operator.add]

    # Agent decision tracking
    agent_thoughts: Annotated[List[str], operator.add]  # Reasoning chain
    evidence_quality_score: float  # 0-1 assessment
    should_continue: bool  # Loop control
    termination_reason: Optional[str]

    # Internal routing state (transient, not persisted) - kept for backward compatibility
    _next_tool: Optional[str]  # Tool selected by agent
    _tool_args: Optional[Dict[str, Any]]  # Arguments for selected tool

    # Final outputs
    final_answer: Optional[str]
    final_confidence: Optional[float]
    final_json: Optional[Dict[str, Any]]

    # Structured synthesis response (generated by terminal synthesis node)
    # Contains guaranteed SynthesisResponse from llm.with_structured_output()
    structured_response: Optional[Any]  # SynthesisResponse | Dict[str, Any]

    # Telemetry
    telemetry: Annotated[List[Dict[str, Any]], operator.add]
    errors: Annotated[List[Dict[str, Any]], operator.add]
